#include <stdio.h>
#include <unistd.h>
void 	print_array(char *arr);
void	ft_strcpy(char *dest, char *src);
void	ft_strncpy(char *dest, char *src, int n);
int		ft_str_is_alpha(char *str);
int		ft_str_is_numeric(char *str);
int 	ft_str_is_lowercase(char *str); 
int 	ft_str_is_uppercase(char *str); 
int		ft_str_is_printable(char *str);
char 	*ft_strupcase(char *str);


int	main(void)
{
	printf("************************\n");
	printf("ex00 copy\n");
	char src[] = "123456789";
	char dst[9];
   	printf("param : %s\n", src);
	ft_strcpy(dst, src);
    	printf("res : %s\n", dst);
	printf("\n");
	printf("**************************\n");
    	printf("**************************\n");
	printf("ex01 -- strncpy\n");
        char src3[] = "aaaaaaaa123456789";
   	printf("param : %s\n", src3);
	ft_strncpy(dst, src3, 10);
        printf("res : %s\n", dst);
    	printf("**************************\n");
	printf("ex02 -- is alpha\n");
	char src2[] = "FFFFFFFFFSFFDSGVSAFTHFSHHF";
	char dst2[] = "aaaaaaaaaaaaaaavcxcvxcdssdasdsf";
	char dst3[] = "aaaFF[]";
	char *dst4 = "aaF";
	int i;
	i = ft_str_is_alpha(src2);
	printf("res : %d -- %s\n", i, src2);	
	i = ft_str_is_alpha(dst2);
    printf("res : %d -- %s\n", i, dst2);		
    i = ft_str_is_alpha(dst3);    
    printf("res : %d -- %s\n", i, dst3);
    i = ft_str_is_alpha(dst4);    
    printf("res : %d -- %s\n", i, dst4);
	printf("\n");
	printf("**************************\n");
	printf("ex03 -- is_number\n");
	char *numb1 = "123456789";
	char *numb2 = "1234567890a";
	i = ft_str_is_numeric(numb1);
    printf("res : %d -- %s\n", i, numb1);	
	i = ft_str_is_numeric(numb2);
    printf("res : %d -- %s\n", i, numb2);	
	printf("**************************");
	printf("ex04 -- is lowercase\n");
	i = ft_str_is_lowercase(src2);
	printf("res : %d -- %s\n", i, src2);
	i = ft_str_is_lowercase(dst2);
	printf("res : %d -- %s\n", i, dst2);
	i = ft_str_is_lowercase(dst3);
	printf("res : %d -- %s\n", i, dst3);
	i = ft_str_is_lowercase(dst4);
	printf("res : %d -- %s\n", i, dst4);
	printf("\n");
	printf("**************************");
	printf("ex05 is uppercase \n");
	i = ft_str_is_uppercase(src2);
	printf("res : %d -- %s\n", i, src2);
	i = ft_str_is_uppercase(dst2);
	printf("res : %d -- %s\n", i, dst2);
	i = ft_str_is_uppercase(dst3);
	printf("res : %d -- %s\n", i, dst3);
	i = ft_str_is_uppercase(dst4);
	printf("res : %d -- %s\n", i, dst4);
	printf("\n");
	printf("**************************");
	printf("ex06 is printable\n");
	i = ft_str_is_printable(src2);
	printf("res : %d -- %s\n", i, src2);
	i = ft_str_is_printable(dst2);
	printf("res : %d -- %s\n", i, dst2);
	i = ft_str_is_printable(dst3);
	printf("res : %d -- %s\n", i, dst3);
	char *dst5 = "sdasdasdsBad\x20sadC\x00";
	i = ft_str_is_printable(dst5);
	printf("res : %d -- %s\n", i, dst5);
	printf("\n**************************\n");
	printf("ex07 upcase\n");
	char *str;
	str = ft_strupcase(src2);
	printf("res : %s -- %s\n", str, src2);
	str = ft_strupcase(dst2);
	printf("res : %s -- %s\n", str, dst2);
	str = ft_strupcase(dst3);
	printf("res : %s -- %s\n", str, dst3);
	str = ft_strupcase(dst4);
	printf("res : %s -- %s\n", str, dst4);
	str = ft_strupcase(dst5);
	printf("res : %s -- %s\n", str, dst5);
	printf("\n**************************\n");
	printf("ex08\n");
	printf("\n");
	printf("\n");
	return(0);
}
